//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Job_Broker_Online.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Profile
    {
        public int StudentId { get; set; }
        public string FullName { get; set; }
        public string IsMaoriOrPacific { get; set; }
        public string Gender { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public string ContactNumber { get; set; }
        public string Email { get; set; }
        public string PhysicalAddress { get; set; }
        public string PostalAddress { get; set; }
        public string Institute { get; set; }
        public string QualificationTitle { get; set; }
        public Nullable<System.DateTime> QualificationCompletionDate { get; set; }
        public string EnrollmentStatus { get; set; }
        public string JobExpection { get; set; }
    
        public virtual Student Student { get; set; }
    }
}
