//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Job_Broker_Online.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentCase
    {
        public int StudentId { get; set; }
        public string FullName { get; set; }
        public string ContactNumber { get; set; }
        public string StudentEmailLink { get; set; }
        public string QualificationTitle { get; set; }
        public string RecommendedJobs { get; set; }
        public string Progress { get; set; }
        public string ProfileLink { get; set; }
        public string ExplanatoryComments { get; set; }
    
        public virtual Student Student { get; set; }
    }
}
